### ISSUE TITLE
upx在网速慢的情况下，put文件夹经常会卡住

### ISSUE THREAD

**Issue by imseon** [upyun/upx#18]
帮忙看下，网速慢的情况下，批量put一个文件夹内的文件，很大概率会卡住，类似下面这样
/huixuan/assets/M...ign-Iconic-Font.woff WAIT [--------------------------------------------------------------------]   0%
/huixuan/assets/fontawesome-webfont.svg  WAIT [========================================================>-----------]  84%
/huixuan/assets/M...sign-Iconic-Font.ttf WAIT [--------------------------------------------------------------------]   0%
/huixuan/assets/M...gn-Iconic-Font.woff2 WAIT [--------------------------------------------------------------------]   0%
/huixuan/assets/fontawesome-webfont.eot  WAIT [--------------------------------------------------------------------]   0%
/huixuan/assets/fontawesome-webfont.woff WAIT [--------------------------------------------------------------------]   0%

没上传完的文件等多久都不走进度，很大概率，导致我在网络稍差的情况下，文件没法更新，多次尝试总会卡在不同的地方，请帮忙解决，辛苦

**Comment by polym** [comment]
请问下这些文件的平均大小在多少左右，如果超过 1M，就可以使用断点续传接口，我这边支持下就可以了。

**Comment by imseon** [comment]
会超过1M的，有字体文件和图片。能支持断点续传最好了，我看sync方法好像不会卡住。会不会跟并发有关系呢？
但是sync我在使用过程中遇到过没有上传过的文件也显示exist，但访问还是404的情况，所以现在这两种方法经常都用不了

**Comment by polym** [comment]
> 会不会跟并发有关系呢？

这个我压测看，理论上是不会有这个问题的。

> 但是sync我在使用过程中遇到过没有上传过的文件也显示exist，但访问还是404的情况，所以现在这两种方法经常都用不了

sync 是基于本地文件系统增量同步的。比如将本地磁盘目录同步到又拍云之后，这时如果删除掉又拍云中的文件，使用 sync 也是无法同步的。
