### ISSUE TITLE
同步目录问题 

### ISSUE THREAD

**Issue by WuYunlong** [upyun/upx#35]
现在服务器上的目录结构是这样
要同步的目录在 /data/img 下

要同步的文件为
/00/01/0001123123123.jpg

我执行的操作为
cd /data/img 

~/upx login 
执行登录操作   登录成功

~/upx put ./* ./
执行文件上传 把当前目录下的文件全部上传到云储存跟目录

我的本意是要直接放在云存储的根目录   /00/01/0001123123123.jpg

结果上传上去的目录是 /01/01/0001123123123.jpg

请问是什么问题。

**Comment by polym** [comment]
本地：/data/img/00/01/0001123123123.jpg
预期又拍云存储：/00/01/0001123123123.jpg

请问是这样么？

**Comment by WuYunlong** [comment]
@polym 是的 我本意是这样的 但是同步上去之后   就会变成 /01/01/0001123123123.jpg

**Comment by polym** [comment]
![image](https://user-images.githubusercontent.com/2860926/38287599-1e49837c-37fe-11e8-9d0f-e2b81ffab084.png)
我这边测试没有复现您说的问题。
