### ISSUE TITLE
增量同步后已有文件的时间信息也被修改了

### ISSUE THREAD

**Issue by 5chenglin** [upyun/upx#52]
RT

**Comment by 5chenglin** [comment]
纠正：指第一次使用增量同步时，会将所有原来的时间信息都修改掉，第二次使用时无这个问题。

**Comment by polym** [comment]
![image](https://user-images.githubusercontent.com/2860926/76158960-7c607780-6156-11ea-9454-b685867406da.png)
我这边测试只有 access 发生了改变

**Comment by polym** [comment]
是指云存储上已有的文件时间信息会被改变么？
因为默认模式下，是通过跟本地数据库做比对，上传增量的，因此第一次上传的时候，本地数据库为空，所以所有文件都会被上传一次。
如果想要已有的文件信息不被改变的话，可以加上 `--strong` ，开启强一致性，每次上传文件之前会判断，是否已经存在。但是这个方式下，效率会低一些。

**Comment by 5chenglin** [comment]
> 是指云存储上已有的文件时间信息会被改变么？
> 因为默认模式下，是通过跟本地数据库做比对，上传增量的，因此第一次上传的时候，本地数据库为空，所以所有文件都会被上传一次。
> 如果想要已有的文件信息不被改变的话，可以加上 `--strong` ，开启强一致性，每次上传文件之前会判断，是否已经存在。但是这个方式下，效率会低一些。

指的大概是我在8:00手动上传过一次目录A，这个目录里只有一个文件a，然后又在A目录里边放了b文件，此时我将A目录增量同步，完成之后，a文件的更新时间就会变成和b一样，但是之后的增量同步操作后，不会出现这个问题 。
我也不太清楚这个算不算bug，也可能是我对增量同步的理解有问题，谢谢您的解答。

**Comment by polym** [comment]
我的理解是，先通过 put 上传了目录，然后在使用 sync 去同步目录。这个是符合预期的，你可以看下我上面的回复。sync 默认只跟本地数据库比对，是一个独立的子命令，put 不会记录到本地数据库。

**Comment by 5chenglin** [comment]
> 我的理解是，先通过 put 上传了目录，然后在使用 sync 去同步目录。这个是符合预期的，你可以看下我上面的回复。sync 默认只跟本地数据库比对，是一个独立的子命令，put 不会记录到本地数据库。

好的，大致明白了。
