### ISSUE TITLE
npx put命令相关 

### ISSUE THREAD

**Issue by ventoso** [upyun/upx#57]
linux下
我在执行`npx put file/ /`的时候，会将file文件夹上传到云端 根目录，请问是否能只将file文件夹下的文件上传至云端根目录而不是file文件夹

很喜欢这种命令行工具，谢谢维护与更新

**Comment by ventoso** [comment]
可以添加支持通配符吗

**Comment by huangnauh** [comment]
新版本已经支持了这个需求，欢迎使用 
`upx upload file/* /`
