### ISSUE TITLE
文件删除后sync任然显示存在

### ISSUE THREAD

**Issue by typ431127** [upyun/upx#67]
我已经在控制台把文件和目录都删除了，但是upx sync任然显示文件存在
版本:upx version v0.3.5 linux/amd64 go1.15.8
另外我的文件发生了变动用sync也没有同步，是否可以增加文件对比更新功能?

**Comment by polym** [comment]
为了使效率更高，upx 默认是跟本地的 leveldb 存储的数据信息作比较的。因此，如果通过控制台操作的话，那么，就会出现 leveldb 中数据信息未更新的情况。

对于你的问题，可以增加以下参数来处理。同步文件时会强制跟云存储中作比较。但是这种方式会损耗一些性能。

```
--strong  strong consistency
```

**Comment by typ431127** [comment]
> 为了使效率更高，upx 默认是跟本地的 leveldb 存储的数据信息作比较的。因此，如果通过控制台操作的话，那么，就会出现 leveldb 中数据信息未更新的情况。
> 
> 对于你的问题，可以增加以下参数来处理。同步文件时会强制跟云存储中作比较。但是这种方式会损耗一些性能。
> 
> ```
> --strong  strong consistency
> ```

感谢！
