### ISSUE TITLE
建议更改 Release 文件名

### ISSUE THREAD

**Issue by mritd** [upyun/upx#99]
目前尝试在 CI 环境中集成  upx 命令(docker 多平台构建), 遇到问题是当前 UPX 的 Release 并没有使用传统的 go 风格架构字符串, 例如 `amd64`、`arm64` 等, 也没有使用 `uname -m` 的输出格式; 这导致必须借助一些脚本来做兼容判断.

当前 Release 发布物文件名称后缀似乎是当时根据 [godownloader](https://github.com/goreleaser/godownloader) 生成的; 而项目内的 install.sh 已经完全不可用, 且 goreleaser 已停止维护; 是否考虑重新调整发布物文件名称或者修复自动安装脚本?

**Comment by huangnauh** [comment]
我调整了下，新版本已经使用默认格式了，之前为了兼容旧版本名称保留下来的，[godownloader](https://github.com/goreleaser/godownloader) 已经不再用了， 现在是通过 [goreleaser](https://github.com/goreleaser/goreleaser) 构建的
